replicaCount: 1

image:
  tag: "latest"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30080

livenessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 3
  periodSeconds: 5
  failureThreshold: 5
